# Generated by Django 5.2.12 on 2026-05-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querymodel',
            name='context',
            field=models.TextField(blank=True),
        ),
    ]
