# Generated by Django 5.2.12 on 2026-05-09 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('canonical_name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('person', 'Person'), ('company', 'Company'), ('country', 'Country'), ('Organisation', 'Organisation')], max_length=50)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=0.0)),
                ('mentions', models.IntegerField(default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.news')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlp_app.entity')),
            ],
        ),
    ]
