# Generated by Django 5.2.12 on 2026-05-09 08:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('description', models.CharField(max_length=1000000)),
                ('published_at', models.CharField(blank=True, null=True)),
                ('url', models.CharField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('embedding_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField()),
                ('last_fetched_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'feeds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=1000000)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
