# Generated by Django 5.2.12 on 2026-05-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='scope',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'managed': True},
        ),
    ]
