# Generated by Django 5.2.12 on 2026-05-10 16:48

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_news_options_alter_scope_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="summary",
            field=models.TextField(
                blank=True,
                null=True
            )
        ),

        migrations.AddField(
            model_name="news",
            name="processed",
            field=models.BooleanField(
                default=False
            ),
        ),

        migrations.AddField(
            model_name="news",
            name="cluster_id",
            field=models.IntegerField(
                blank=True,
                null=True
            ),
        ),

        migrations.AddField(
            model_name="news",
            name="embedding_id",
            field=models.CharField(
                max_length=255,
                blank=True,
                null=True
            ),
        ),
    ]
