# Generated by Django 5.2.12 on 2026-05-22 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20260510_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='feed',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.scope'),
        ),
        migrations.AddField(
            model_name='scope',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tag'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scope',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
